env:
- CF_VERSION=3.8.0
- CF_VERSION=3.7.2
- CF_VERSION=3.6.6

install:
- wget https://cfengine-package-repos.s3.amazonaws.com/community_binaries/cfengine-community_$CF_VERSION-1_amd64.deb
- sudo dpkg -i cfengine-community_$CF_VERSION-1_amd64.deb
- ls

script:
- cd $TRAVIS_BUILD_DIR
- ./autogen.sh --without-core --prefix=$TRAVIS_BUILD_DIR/install
- make install
- /var/cfengine/bin/cf-promises -f $TRAVIS_BUILD_DIR/install/masterfiles/promises.cf
- /var/cfengine/bin/cf-promises -f $TRAVIS_BUILD_DIR/install/masterfiles/update.cf
