language: c

matrix:
  include:

    # JOB 0  --  first because it's the fastest
    - env: STYLE_CHECK_JOB=1

    # JOB 1
    - env: CF_VERSION=latest
      addons:
        apt:
          sources:
            - sourceline: "deb https://cfengine-package-repos.s3.amazonaws.com/pub/apt/packages stable main"
            - key_url: https://cfengine-package-repos.s3.amazonaws.com/pub/gpg.key
          packages:
            - cfengine-community

    # JOB 2
    - env: CF_VERSION=lts
      addons:
        apt:
          sources:
            - sourceline: "deb https://cfengine-package-repos.s3.amazonaws.com/pub/apt/packages stable main"
            - key_url: https://cfengine-package-repos.s3.amazonaws.com/pub/gpg.key
          packages:
            - cfengine-community=3.7.4-1


script:
- INSTDIR=$HOME/cf_install
- cd $TRAVIS_BUILD_DIR
- if [ x$STYLE_CHECK_JOB = x1 ]; then sh tests/style_check.sh; exit; fi
- ./autogen.sh --without-core --prefix=$INSTDIR
- make install
- /var/cfengine/bin/cf-promises --version
- /var/cfengine/bin/cf-promises -c -I -f $INSTDIR/masterfiles/update.cf
- /var/cfengine/bin/cf-promises -c -I -f $INSTDIR/masterfiles/promises.cf
- make dist
- export DIST_TARBALL=cfengine-masterfiles-*.tar.gz
- make tar-package
- export PKG_TARBALL=cfengine-masterfiles-*.pkg.tar.gz


# We deploy when setting tags only, which basically never happens
# on master branch. Cherry-pick this part and alter it properly into
# the release branches.

deploy:
  skip_cleanup: true
  provider: releases
  # Remember to set it as private variable in Travis-CI settings
  api_key: "$GITHUB_RELEASE_TOKEN"
  file:
  - "$DIST_TARBALL"
  - "$PKG_TARBALL"
  on:
    tags: true
    # Avoid upload from all the multiple parallel matrix jobs
    condition: "$CF_VERSION = latest"
